"""Add is_admin field

Revision ID: 5107090deaa4
Revises: 
Create Date: 2025-07-02 04:03:48.988463

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5107090deaa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
